---
functional:
  - Пользователь должен иметь возможность зарегистрироваться
  - Пользователь должен иметь возможность авторизоваться
  - Пользователь должен иметь вохможность создавать игру
  - Пользователь должен иметь возможность выбирать уровень сложности, тип игры и время на игру
  - Пользователь должен иметь возможность выбирать тип задачи
  - Пользователь должен иметь возможность фильтровать задачи при создании игры
  - Пользователь должен иметь возмонжость выбрать язык программирования
  - Пользователь должен видеть код другого пользователя во время игры
  - Пользователь должен иметь возможность видеть отведенное время на игру и описание задания
  - Пользователь во время игры может сменить язык
  - Пользователь имеет неограниченное количество попыток для проверки своего решения
  - Пользователь должен иметь возможность увидеть модальное окно с информацией кто выиграл
  - Пользователь должен иметь возможность доиграть, в случае проигрыша
  - Пользователь должен иметь возможность вернуться в игру в случае вылета
  - Пользователь, который зарегистрирован должен иметь возможность пользоваться чатом
  - Пользователь должен получать очки рейтинга
  - Пользователь может следить за ходом чужой игры
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Сайт должен быть кроссплатформенным
implicit:
  - Игра должна считаться законченной, когда оба пользователя вышли из неё
  - Завершенная игра доступна в записи, в которой редактор кода выглядит как проигрыватель
  - На основе очков, должен строится рейтинг за неделю, месяц и за все время
